#!/bin/bash

# Script to check subscription status and fix if needed

EMAIL="hhirawat5bkp@gmail.com"

echo "🔍 Checking Subscription Status for: $EMAIL"
echo "=============================================="
echo ""

echo "1. Check your SERVER CONSOLE LOGS for webhook processing"
echo "   Look for these messages:"
echo "   - 🔔 Webhook received"
echo "   - 🛒 Checkout session completed event"
echo "   - ✅ User updated to PRO plan"
echo "   - OR ❌ Missing userId"
echo ""
echo "2. Check Stripe Dashboard for subscription:"
echo "   https://dashboard.stripe.com/test/subscriptions"
echo "   Look for subscriptions with customer email: $EMAIL"
echo ""
echo "3. If you find a subscription ID (starts with 'sub_'), run:"
echo ""
echo "   node fix-user-subscription.js $EMAIL <subscription_id>"
echo ""
echo "4. Or check database directly:"
echo ""
echo "   Connect to your database and run:"
echo "   SELECT id, email, plan, \"stripeCustomerId\", \"stripeSubscriptionId\""
echo "   FROM \"User\""
echo "   WHERE email = '$EMAIL';"
echo ""
echo "════════════════════════════════════════"
echo "Quick Fix Commands:"
echo "════════════════════════════════════════"
echo ""
echo "If you found the subscription ID in Stripe Dashboard:"
echo ""
echo "  node fix-user-subscription.js $EMAIL sub_xxxxx"
echo ""
echo "To just update plan to PRO (if subscription exists in DB):"
echo ""
echo "  node fix-user-subscription.js $EMAIL"
echo ""

